# Generated by Django 3.2.9 on 2022-09-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.CharField(choices=[('Harare', 'Harare'), ('Bulawayo', 'Bulawayo'), ('Mutare', 'Mutare')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='antivirus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='brand_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='condition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='is_qrent',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='operating_system',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='serial_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.employee'),
        ),
    ]
